# Generated by Django 3.1.4 on 2021-01-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210123_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('offer_discount', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('size', models.CharField(blank=True, default='free_size', max_length=200, null=True)),
                ('stock', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
