# Generated by Django 3.1.4 on 2021-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210205_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
