# Generated by Django 3.1.4 on 2021-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210220_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
