# Generated by Django 3.1.4 on 2021-02-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
