# Generated by Django 3.1.4 on 2021-02-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20210220_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image2',
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
