# Generated by Django 3.1.4 on 2021-02-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_product_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
